twig:
    file_name_pattern: '*.twig'
    # pour utilisation thème bootstrap dans les formulaire générer
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
